import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { TranscendProvider } from "@/lib/transcend-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <TranscendProvider airgapSrc="https://transcend-cdn.com/cm-test/eb535ba5-bb66-4728-af60-8a0ecd7d0788/airgap.js">
        <body className={inter.className}>{children}</body>
      </TranscendProvider>
    </html>
  );
}
